### ISSUE TITLE
Would a new release be possible?

### ISSUE THREAD

**Issue by Whitesttax** [MarvNC/jpdb-freq-list#1]
Hey, thanks for the frequency list, I have been using with yomichan for a bit now and it's great! 
I'm wondering if you plan to update it? So far as I understood, I could download the script and do it myself, but that isn't very feasible as I'm not even sure how you added all of those media to your account. 
If you still have that account, an update would be awesome. Probably due to changes in the way words are morphed, some ranking changes were made. I guess new media could influence this as well but overall you got it covered I think. Example of a quick one:
![image](https://user-images.githubusercontent.com/20992483/212566524-2a0be460-b29e-4c80-9c26-0fec3df5052b.png)
It is still reasonably in line with the site though, so I'm only asking is case it won't be too much trouble! :)

**Comment by MarvNC** [comment]
Nope, unfortunately there is now an account-wide limit on how many vocabulary you can have in all your decks... probably my fault 🤣
If you want, you can generate a deck of the top 30,000 vocabulary with a patreon account and generate a list that will be more up-to-date with the new JPDB calculation changes, but it won't include reading frequencies or words over 30,000 frequency.

**Comment by Whitesttax** [comment]
I created one like this, not sure if I should change anything
![image](https://user-images.githubusercontent.com/20992483/212572276-6c7872fe-f2d3-4486-be59-2cfbb3abcdb6.png)
I got closer results: 
![image](https://user-images.githubusercontent.com/20992483/212572307-a9dc4099-1dcc-4175-bd19-ed80e779e26e.png)

**Comment by MarvNC** [comment]
Yeah that looks good, I wouldn't use any of the exclude features though. It'd just reduce the amount of kana readings you have frequencies for, which is already very little.

**Comment by MarvNC** [comment]
I just tried generating a new deck myself with all the excludes unchecked and 領域 has a frequency of 4020, which seems right as JPDB rounds up to the nearest 100.

**Comment by Whitesttax** [comment]
Thanks for the help, will redo it then and name it properly this time :)
