### ISSUE TITLE
Invalid schema

### ISSUE THREAD

**Issue by uncomputable** [MarvNC/jpdb-freq-list#2]
Hi. I know this dictionary cannot be updated because jpdb changed its rules, but the already released dictionary stopped to work for me. When I import it I get the following error:

> Error: Dictionary has invalid data in 'term_meta_bank_1.json' for value 'dictionary[0][2][1]', validated against 'schema.additionalItems.oneOf[0].items[2][1].items': 0 oneOf schemas matched

This dictionary seems popular, so let's get it fixed :)

**Comment by MarvNC** [comment]
This is because you're on an outdated version of Yomichan. Please check that your Yomichan is up to date with the last [release found here](https://github.com/FooSoft/yomichan/releases).

Alternatively you can try [Yomibaba](https://github.com/forsakeninfinity/yomibaba).
